name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create Release for ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
          - platform: "ubuntu-22.04"
          - platform: "windows-latest"

    runs-on: ${{ matrix.platform }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust cross-compilation targets for macOS
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install Rust toolchain for Windows/Linux
        if: runner.os != 'macOS'
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev

      - name: Install Tauri CLI and Trunk
        run: cargo install tauri-cli trunk

      - name: Build and Create Release (macOS)
        if: runner.os == 'macOS'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--target universal-apple-darwin"
          tagName: ${{ github.ref_name }}
          releaseName: "Kindle Interactive v__VERSION__"
          releaseBody: "See the assets to download this version."
          releaseDraft: true
          prerelease: false

      - name: Build and Create Release (Windows/Linux)
        if: runner.os != 'macOS'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Kindle Interactive v__VERSION__"
          releaseBody: "See the assets to download this version."
          releaseDraft: true
          prerelease: false
